### ISSUE TITLE
Support Arm MPS2 serial interface

### ISSUE THREAD

**Issue by daldr-ntml** [ARM-software/vscode-device-manager#2]
The Arm MPS2 dev board supports a serial interface (via a USB to serial converter cable) but Device Manager reports:

`Serial is not supported for this device`

Could support be added please?

**Comment by thegecko** [comment]
I assume this is on the desktop version of the extension?

This would be due to the serial port not being related to the device via serialnumber, e.g. its using a different usb interface.

In this case, we would need to add a new feature to allow the user to select an arbitrary com port for serial output as there is no way of detecting it automatically.

**Comment by daldr-ntml** [comment]
Thanks. Yes, it is on the desktop version and I am using two USB ports - I think that is inevitable.

**Comment by thegecko** [comment]
@DavidA2014 

We added some support for this in the latest release, does it improve your experience?

**Comment by daldr-ntml** [comment]
@thegecko Thanks for letting me know. I tried it and it looks good. Unfortunately, I'm unable to load my .elf file on the MPS2 at the moment, and so can't test the serial port.

**Comment by thegecko** [comment]
@DavidA2014 I think this is resolved, please re-open it if you require further information.

I assume your flashing issue is:

https://github.com/ARM-software/vscode-embedded-debug/issues/17
